# version: '3.4'

services:
    cms:
        container_name: ${PROJECT_NAME}_cms
        build:
            context: .
            dockerfile: ./services/cms/Dockerfile
            args:
                ROOT: ./services/cms
                ENV: ${ENV}
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWORD: ${DB_PASSWORD}
                DB_PORT: ${DB_PORT}
                DRUPAL_HASH_SALT: ${DRUPAL_HASH_SALT}
                PROJECT_BASE_URL: ${PROJECT_BASE_URL}
        environment:
            ENV: ${ENV}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_PORT: ${DB_PORT}
            PROJECT_BASE_URL: ${PROJECT_BASE_URL}
            SITE_NAME: ${SITE_NAME}
            SITE_MAIL: ${SITE_MAIL}
            ACCOUNT_NAME: ${ACCOUNT_NAME}
            ACCOUNT_MAIL: ${ACCOUNT_MAIL}
            DRUPAL_HASH_SALT: ${DRUPAL_HASH_SALT}
            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_PROTOCOL: ${SMTP_PROTOCOL}
            SMTP_AUTOTLS: ${SMTP_AUTOTLS}
            SMTP_USERNAME: ${SMTP_USERNAME}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            SMTP_FROM: ${SMTP_FROM}
            SMTP_FROMNAME: ${SMTP_FROMNAME}
        depends_on:
            - db
        hostname: oerdynamiccoalition.org
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./services/cms/src/sites:/opt/drupal/web/sites
            - ./services/cms/src/data:/opt/drupal/web/data
            - ./services/cms/src/modules/custom:/opt/drupal/web/modules/custom
            - ./services/cms/src/themes/custom:/opt/drupal/web/themes/custom
        restart: unless-stopped

    db:
        container_name: ${PROJECT_NAME}_db
        build:
            context: .
            dockerfile: ./services/db/Dockerfile
            args:
                ROOT: ./services/db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./services/db/data/mydata:/var/lib/mysql
        restart: unless-stopped

# volumes:
    # db-data:
