FROM drupal:php8.1-fpm-alpine3.16

ARG ROOT

# Install build dependencies
RUN apk add --no-cache bash
RUN apk add --no-cache git
RUN apk add --no-cache mysql-client

# Install modules
RUN touch /.dockerenv
RUN composer require drush/drush:^10.6.2
RUN composer require drupal/admin_toolbar:^3.2.1
RUN composer require drupal/backup_migrate:^5.0
RUN composer require drupal/coder:^8.3.16
RUN composer require drupal/coffee:^1.2
RUN composer require drupal/devel:^5.0.2
RUN composer require drupal/gin_toolbar:^1.0@beta
RUN composer require drupal/gin:^3.0@beta
RUN composer require drupal/pathauto:^1.11
RUN composer require drupal/smtp:^1.2
RUN composer require drupal/drush_language:^1.0@RC
RUN composer require drupal/taxonomy_multidelete_terms:^1.3

# Copy project files from host
COPY $ROOT/drupal.sh ./
# COPY $ROOT/docker-php-entrypoint /usr/local/bin/
# RUN chmod +x /usr/local/bin/docker-php-entrypoint

# TODO: run drupal.sh --install
# CMD ["sh", "-c", "drupal.sh --install"]
# CMD ["bash /opt/drupal/drupal.sh --install"]
# CMD ["pwd && ls -la"]
# ENTRYPOINT ["pwd"]
# ENTRYPOINT ["bash /opt/drupal/drupal.sh --install"]
# ENTRYPOINT ["bash /usr/local/bin/docker-php-entrypoint && cd /opt/drupal && bash drupal.sh --install"]
# ENTRYPOINT ["docker-php-entrypoint"]
