#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"

# Install Drupall  if not already
# echo "Installing Drupal..."
# cd /opt/drupal
# bash drupal.sh --install
