# FROM drupal:10.4.1-php8.3-apache-bookworm
FROM drupal:10.4.1-php8.3-fpm-bookworm

ARG ROOT
ARG ENV
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_PORT
ARG PROJECT_BASE_URL

# Set env variables
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_PORT=${DB_PORT}
ENV PROJECT_BASE_URL=${PROJECT_BASE_URL}

# Copy project files from host
COPY $ROOT/drupal.sh ./
COPY $ROOT/patches ./patches
COPY $ROOT/scripts ./scripts
COPY $ROOT/src/preprocess.php ./web/
COPY $ROOT/config/php.$ENV.ini /usr/local/etc/php/php.ini
COPY $ROOT/config/crontab /var/spool/cron/crontabs/root

# Install build dependencies
RUN apt-get update && apt-get install -y \
    nano \
    unzip \
    default-mysql-client \
    rsync \
    cron \
    gettext \
    && rm -rf /var/lib/apt/lists/*

# Install modules
RUN touch /.dockerenv

RUN bash drupal.sh --config-composer

RUN composer require \
    oomphinc/composer-installers-extender \
    npm-asset/select2 \
    drush/drush:^12.1

RUN bash drupal.sh --get-modules

# Prepare scripts
RUN envsubst < ./scripts/cron_env.sh > /tmp/cron_env.sh && cp /tmp/cron_env.sh ./scripts/cron_env.sh

# Apply patches
RUN bash patches/patch.sh

# Install xdebug
RUN pear config-set php_ini /usr/local/etc/php/php.ini
RUN pecl install xdebug

# Start the cron service and Drupal
# CMD cron && docker-php-entrypoint apache2-foreground
CMD cron && docker-php-entrypoint php-fpm
